name: appwrite_function
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  dart_appwrite: ^3.0.2

  appwrite-function-types:
    git: 
      url: https://github.com/appwrite/function-types.git
      ref: dart-2.15
      
dev_dependencies:
  pedantic: ^1.9.0