name: appwrite_function
description: Dart starter for Appwrite function.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  dart_appwrite: ^3.0.2

dev_dependencies:
  pedantic: ^1.9.0